---
title: "Significance of hydroxylation sites"
author: "Yoichiro Sugimoto"
date: "`r format(Sys.time(), '%d %B, %Y')`"
vignette: >
  %\VignetteIndexEntry{Bioconductor style for PDF documents}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
output:
   html_document:
     highlight: haddock
     toc: yes
     toc_depth: 2
     keep_md: yes
---


# Load packages


```{r load packages}

temp <- sapply(list.files("../functions", full.names = TRUE), source)
set.seed(0)

library("readxl")
library("exact2x2")

results.dir <- file.path("../../results")
jq.dir <- file.path(results.dir, "j-q-misc-analysis")

create.dirs(c(jq.dir))

```

# Analysis


```{r load data}

count.dt <- read_xlsx(
    "../../data/processed_data/Peptide_PD_data_for_fishers_test.xlsx",
    sheet = "new data"
) %>% as.data.table

setnames(
    count.dt,
    old = c(
        "(#K) Peptide PD: HeLa_wt", "(#K) Peptide PD: HeLa_J6KO",
        "(#Kox) Peptide PD: HeLa_wt", "(#Kox)Peptide PD: HeLa_J6KO"
    ),
    new = c("K_all_WT", "K_all_J6KO", "K_ox_WT", "K_ox_J6KO")
)

count.dt[, `:=`(
    K_unmodified_WT = K_all_WT - K_ox_WT,
    K_unmodified_J6KO = K_all_J6KO - K_ox_J6KO
)]

count.dt[
   ,
    c("odds_ratio", "fisher_p") := matrix(
        c(K_ox_WT, K_unmodified_WT, K_ox_J6KO, K_unmodified_J6KO),
        nrow = 2,
        dimnames = list(
            K_modification = c("hydroxylated", "unmodified"),
            JMJD6 = c("WT", "J6KO")
        )
    ) %>%
        {list(
             odds_ratio = fisher.test(.)$estimate,
             p_value = fisher.test(.)$p.value
         )},
    by = seq_len(nrow(count.dt))
]

count.dt[
   ,
    boschloo_p := boschloo(
        x1 = K_ox_WT, n1 = K_all_WT,
        x2 = K_ox_J6KO, n2 = K_all_J6KO,
        alternative = "two.sided"
    )$p.value,
    by = seq_len(nrow(count.dt))
]

library("ggplot2")

ggplot(
    count.dt,
    aes(
        x = log10(fisher_p),
        y = log10(boschloo_p)
    )
) + geom_point()

count.dt[, `:=`(
    fisher_fdr = p.adjust(fisher_p, method = "fdr"),
    boschloo_fdr = p.adjust(boschloo_p, method = "fdr")
)]

fwrite(
    count.dt,
    file.path(jq.dir, "significance-of-hydroxylation-site-v2.csv")
)


```

